<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><title>Comparison of Binary Diagnostic Tests in a Paired Study Design — DTComPair-package • DTComPair</title><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet"><script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.4.2/css/all.min.css" rel="stylesheet"><link href="../deps/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet"><script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Comparison of Binary Diagnostic Tests in a Paired Study Design — DTComPair-package"><meta name="description" content="Comparison of the accuracy of two binary diagnostic tests in a &amp;#8220;paired&amp;#8221; study design, i.e. when each test is applied to each subject in the study."><meta property="og:description" content="Comparison of the accuracy of two binary diagnostic tests in a &amp;#8220;paired&amp;#8221; study design, i.e. when each test is applied to each subject in the study."><meta property="og:image" content="https://chstock.github.io/DTComPair/logo.png"></head><body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-light" data-bs-theme="light" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">DTComPair</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">1.2.4</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto"><li class="active nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul><ul class="navbar-nav"><li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json"></form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/chstock/DTComPair/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul></div>


  </div>
</nav><div class="container template-reference-topic">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.png" class="logo" alt=""><h1>Comparison of Binary Diagnostic Tests in a Paired Study Design</h1>

      <div class="d-none name"><code>dtcompair-package.rd</code></div>
    </div>

    <div class="ref-description section level2">
    <p>Comparison of the accuracy of two binary diagnostic tests in a “paired” study design, i.e. when each test is applied to each subject in the study.</p>
    </div>


    <div class="section level2">
    <h2 id="details">Details<a class="anchor" aria-label="anchor" href="#details"></a></h2>


<p>The accuracy measures that can be compared in the present version are sensitivity, specificity, positive and negative predictive values, and positive and negative diagnostic likelihood ratios.</p>
<p>It is required that results from a binary gold-standard test are also available.</p>
<p>Methods for comparison of sensitivity and specificity: McNemar test (McNemar, 1947) and exact binomial test. Further, several methods to compute confidence intervals for differences in sensitivity and specificity are implemented.</p>
<p>Methods for comparison of positive and negative predictive values: generalized score statistic (Leisenring, Alonzo and Pepe, 2000), weighted generalized score statistic (Kosinski, 2013) and comparison of relative predictive values (Moskowitz and Pepe, 2006).</p>
<p>Methods for comparison of positive and negative diagnostic likelihood ratios: a regression model approach (Gu and Pepe, 2009).</p>
<p>For a general introduction into the evaluation of diagnostic tests see e.g. Pepe (2003), Zhou, Obuchowski and McClish (2011).</p>
    </div>
    <div class="section level2">
    <h2 id="author">Author<a class="anchor" aria-label="anchor" href="#author"></a></h2>
    <p>Christian Stock, Thomas Hielscher and Andrea Discacciati</p>
<p>Maintainer: Christian Stock &lt;christian.stock@boehringer-ingelheim.com&gt;</p>
    </div>
    <div class="section level2">
    <h2 id="references">References<a class="anchor" aria-label="anchor" href="#references"></a></h2>
    <p>Gu and Pepe (2009), "Estimating the capacity for improvement in risk prediction with a marker", &lt;doi:10.1093/biostatistics/kxn025&gt;.</p>
<p>Kosinski (2013), "A weighted generalized score statistic for comparison of predictive values of diagnostic tests", &lt;doi:10.1002/sim.5587&gt;.</p>
<p>Leisenring, Alonzo and Pepe (2000), "Comparisons of predictive values of binary medical diagnostic tests for paired designs", &lt;doi:10.1111/j.0006-341X.2000.00345.x&gt;.</p>
<p>McNemar (1947), "Note on the sampling error of the difference between correlated proportions or percentages",  &lt;doi:10.1007/BF02295996&gt;.</p>
<p>Moskowitz and Pepe (2006), "Comparing the predictive values of diagnostic tests: sample size and analysis for paired study designs", &lt;doi:10.1191/1740774506cn147oa&gt;.</p>
<p>Pepe (2003, ISBN:978-0198509844), "The statistical evaluation of medical tests for classification and prediction".</p>
<p>Zhou, Obuchowski and McClish (2011), "Statistical Methods in Diagnostic Medicine", &lt;doi:10.1002/9780470906514&gt;.</p>
    </div>
    <div class="section level2">
    <h2 id="see-also">See also<a class="anchor" aria-label="anchor" href="#see-also"></a></h2>
    <div class="dont-index"><p>Data management functions: <code><a href="tab.1test.html">tab.1test</a></code>, <code><a href="tab.paired.html">tab.paired</a></code>, <code><a href="read.tab.paired.html">read.tab.paired</a></code>, <code><a href="generate.paired.html">generate.paired</a></code> and <code><a href="represent.long.html">represent.long</a></code>.</p>
<p>Computation of standard accuracy measures for a single test: <code><a href="acc.1test.html">acc.1test</a></code> and <code><a href="acc.paired.html">acc.paired</a></code>.</p>
<p>Comparison of sensitivity and specificity: <code><a href="sesp.mcnemar.html">sesp.mcnemar</a></code>, <code><a href="sesp.exactbinom.html">sesp.exactbinom</a></code> and <code><a href="sesp.diff.ci.html">sesp.diff.ci</a></code>.</p>
<p>Comparison of positive and negative predictive values: <code><a href="pv.gs.html">pv.gs</a></code>, <code><a href="pv.wgs.html">pv.wgs</a></code> and <code><a href="pv.rpv.html">pv.rpv</a></code>.</p>
<p>Comparison of positive and negative diagnostic likelihood ratios: <code><a href="dlr.regtest.html">dlr.regtest</a></code> and <code><a href="DLR.html">DLR</a></code>.</p></div>
    </div>

    <div class="section level2">
    <h2 id="ref-examples">Examples<a class="anchor" aria-label="anchor" href="#ref-examples"></a></h2>
    <div class="sourceCode"><pre class="sourceCode r"><code><span class="r-in"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="va">Paired1</span><span class="op">)</span> <span class="co"># Hypothetical study data </span></span></span>
<span class="r-in"><span><span class="va">hsd</span> <span class="op">&lt;-</span> <span class="fu"><a href="tab.paired.html">tab.paired</a></span><span class="op">(</span>d<span class="op">=</span><span class="va">d</span>, y1<span class="op">=</span><span class="va">y1</span>, y2<span class="op">=</span><span class="va">y2</span>, data<span class="op">=</span><span class="va">Paired1</span><span class="op">)</span></span></span>
<span class="r-in"><span><span class="fu"><a href="acc.paired.html">acc.paired</a></span><span class="op">(</span><span class="va">hsd</span><span class="op">)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> Diagnostic accuracy of test 'y1'</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> (Estimates, standard errors and Wald's asymptotic normal-based 95%-confidence intervals)</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>                  Est.         SE  Lower CL  Upper CL</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> Sensitivity 0.8802661 0.01528718 0.8503038 0.9102284</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> Specificity 0.6781609 0.02891782 0.6214830 0.7348388</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> PPV         0.8253638 0.01731081 0.7914353 0.8592924</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> NPV         0.7662338 0.02784617 0.7116563 0.8208113</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>            Est.  SE (log)  Lower CL  Upper CL</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> PDLR  2.7351124 0.0915147 2.2860079 3.2724472</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> NDLR  0.1765568 0.1346088 0.1356142 0.2298601</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> ----------------------------------------------------------</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> Diagnostic accuracy of test 'y2'</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> (Estimates, standard errors and Wald's asymptotic normal-based 95%-confidence intervals)</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>                  Est.         SE  Lower CL  Upper CL</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> Sensitivity 0.7560976 0.02022128 0.7164646 0.7957305</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> Specificity 0.7969349 0.02490054 0.7481307 0.8457390</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> PPV         0.8654822 0.01718980 0.8317908 0.8991736</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> NPV         0.6540881 0.02667395 0.6018081 0.7063680</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>            Est.  SE (log)  Lower CL  Upper CL</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> PDLR  3.7234238 0.1255060 2.9114648 4.7618247</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> NDLR  0.3060507 0.0885996 0.2572629 0.3640906</span>
<span class="r-in"><span><span class="fu"><a href="sesp.mcnemar.html">sesp.mcnemar</a></span><span class="op">(</span><span class="va">hsd</span><span class="op">)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $sensitivity</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>          test1          test2           diff test.statistic        p.value </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   8.802661e-01   7.560976e-01  -1.241685e-01   3.136000e+01   2.143518e-08 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $specificity</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>          test1          test2           diff test.statistic        p.value </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   6.781609e-01   7.969349e-01   1.187739e-01   1.281333e+01   3.441579e-04 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $method</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] "mcnemar"</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-in"><span><span class="fu"><a href="pv.rpv.html">pv.rpv</a></span><span class="op">(</span><span class="va">hsd</span><span class="op">)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $ppv</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>          test1          test2           rppv    se.log.rppv       lcl.rppv </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>     0.82536383     0.86548223     1.04860694     0.01991247     1.00847050 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>       ucl.rppv test.statistic        p.value </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>     1.09034078     2.38355929     0.01714612 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $npv</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>          test1          test2           rnpv    se.log.rnpv       lcl.rnpv </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   7.662338e-01   6.540881e-01   8.536403e-01   3.783679e-02   7.926258e-01 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>       ucl.rnpv test.statistic        p.value </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   9.193516e-01  -4.182314e+00   2.885568e-05 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $Sigma</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>              log.rppv     log.rnpv</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> log.rppv 0.0003965065 0.0004024578</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> log.rnpv 0.0004024578 0.0014316223</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $method</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] "relative predictive values (rpv)"</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $alpha</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.05</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-in"><span><span class="fu"><a href="dlr.regtest.html">dlr.regtest</a></span><span class="op">(</span><span class="va">hsd</span><span class="op">)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $pdlr</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $pdlr$test1</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 2.735112</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $pdlr$test2</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 3.723424</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $pdlr$ratio</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.7345692</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $pdlr$se.log</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.1326086</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $pdlr$test.statistic</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] -2.326177</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $pdlr$p.value</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.0200091</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $pdlr$lcl</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.5664428</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $pdlr$ucl</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.9525973</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $ndlr</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $ndlr$test1</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.1765568</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $ndlr$test2</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.3060507</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $ndlr$ratio</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.5768875</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $ndlr$se.log</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.137376</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $ndlr$test.statistic</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] -4.004396</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $ndlr$p.value</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 6.217627e-05</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $ndlr$lcl</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.4407136</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $ndlr$ucl</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.7551371</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $alpha</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] 0.05</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> $method</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] "DLR regression model (regtest)"</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
</code></pre></div>
    </div>
  </main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside></div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by Christian Stock, Thomas Hielscher, Andrea Discacciati.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.1.0.</p>
</div>

    </footer></div>





  </body></html>

